"""Turn ARTICLE.md into files Medium can actually use.

Medium has no Markdown import, and it cannot resolve a relative path such as
`img/ui-console.png`. This script writes three things next to the article:

  ARTICLE_MEDIUM.md    the article with every image as an absolute GitHub URL
  medium_paste.html    the article rendered, for open-in-browser -> copy -> paste
  IMAGES.md            the ten images in order, with where each goes and its
                       caption, for placing them by hand

    python docs/medium/build_medium.py

The images are served from raw.githubusercontent.com on the branch below, so
they must be committed and pushed before the pasted article can load them.
"""
from __future__ import annotations

import html
import re
from pathlib import Path

import markdown

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "ARTICLE.md"
BRANCH = "sentinel-v2"
RAW_BASE = f"https://raw.githubusercontent.com/r-rishit27/hacker_house/{BRANCH}/docs/medium"
BLOB_BASE = f"https://github.com/r-rishit27/hacker_house/blob/{BRANCH}/docs/medium"

# [ \t]*$, not \s*$: \s would swallow the newline and the blank line after
# the image, gluing it onto the next paragraph -- or into the next heading.
IMAGE = re.compile(r"^!\[(?P<alt>[^\]]*)\]\((?P<path>img/[^)]+)\)[ \t]*$", re.MULTILINE)


def absolute_markdown(text: str) -> str:
    return IMAGE.sub(lambda m: f"![{m['alt']}]({RAW_BASE}/{m['path']})", text)


def nearest_heading(text: str, pos: int) -> str:
    """The section an image sits in, so it can be found in Medium's editor."""
    heads = [m for m in re.finditer(r"^(#{2,3}) (.+)$", text, re.MULTILINE)
             if m.start() < pos]
    return heads[-1].group(2).strip() if heads else "(before the first section)"


def preceding_line(text: str, pos: int) -> str:
    """What sits directly above the image: the paste anchor in the editor.

    A heading counts. An image placed straight under "## The architecture" must
    be anchored to that heading, not to the last paragraph of the section
    before it.
    """
    for line in reversed(text[:pos].rstrip().splitlines()):
        line = line.strip()
        if not line or line.startswith(("!", "---", "```")):
            continue
        if line.startswith("#"):
            return "the heading " + line.lstrip("#").strip()
        line = re.sub(r"[*_`]", "", line)
        line = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", line)
        return line[:90] + ("..." if len(line) > 90 else "")
    return "(top of the article)"


def image_rows(text: str) -> list[dict]:
    rows = []
    for i, m in enumerate(IMAGE.finditer(text), 1):
        rows.append({
            "n": i,
            "file": m["path"].split("/")[-1],
            "alt": m["alt"],
            "section": nearest_heading(text, m.start()),
            "after": preceding_line(text, m.start()),
            "raw": f"{RAW_BASE}/{m['path']}",
            "blob": f"{BLOB_BASE}/{m['path']}",
        })
    return rows


def pasteable_html(md_text: str) -> str:
    """Render for pasting. Images become <figure> so Medium keeps the caption."""
    body = markdown.markdown(md_text, extensions=["fenced_code"])

    def to_figure(m: re.Match) -> str:
        src, alt = m["src"], html.unescape(m["alt"])
        return (f'<figure><img src="{src}" alt="{html.escape(alt)}">'
                f"<figcaption>{html.escape(alt)}</figcaption></figure>")

    body = re.sub(r'<p><img alt="(?P<alt>[^"]*)" src="(?P<src>[^"]+)" ?/?></p>',
                  to_figure, body)
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Sentinel - paste into Medium</title>
<style>
  body {{ max-width: 740px; margin: 40px auto; padding: 0 16px;
         font: 18px/1.6 Georgia, serif; color: #222; background: #fff; }}
  .note {{ font: 14px/1.5 system-ui, sans-serif; background: #fff8dc;
           border: 1px solid #e0c060; padding: 12px 16px; border-radius: 6px; }}
  img {{ max-width: 100%; height: auto; }}
  figcaption {{ font: 14px system-ui, sans-serif; color: #666; text-align: center; }}
  pre {{ background: #f4f4f4; padding: 12px; overflow-x: auto; font-size: 14px; }}
  code {{ font-size: 15px; }}
</style></head><body>
<div class="note"><b>How to use this page:</b> wait for all ten images to load,
then press Ctrl+A, Ctrl+C and paste into a new Medium story with Ctrl+V.
Delete this yellow box after pasting. Full steps: docs/medium/IMAGES.md.</div>
{body}
</body></html>
"""


def images_guide(rows: list[dict]) -> str:
    lines = [
        "# Placing the images in Medium",
        "",
        "Generated by `build_medium.py`. Ten images, in the order they appear in",
        "the article. Use this if Medium drops any images when you paste, or if",
        "you would rather place them by hand.",
        "",
        "Each image has a download link (click it, then save), the section it",
        "belongs in, the line of text it goes **directly under**, and the caption",
        "to type beneath it.",
        "",
    ]
    for r in rows:
        lines += [
            f"## {r['n']}. `{r['file']}`",
            "",
            f"- **Download:** [{r['file']}]({r['raw']})",
            f"- **Section:** {r['section']}",
            f"- **Goes directly under:** \"{r['after']}\"",
            f"- **Caption / alt text:**",
            "",
            f"  > {r['alt']}",
            "",
        ]
    return "\n".join(lines) + "\n"


def main() -> None:
    text = SOURCE.read_text(encoding="utf-8")
    rows = image_rows(text)
    md_abs = absolute_markdown(text)

    (HERE / "ARTICLE_MEDIUM.md").write_text(md_abs, encoding="utf-8")
    (HERE / "medium_paste.html").write_text(pasteable_html(md_abs), encoding="utf-8")
    (HERE / "IMAGES.md").write_text(images_guide(rows), encoding="utf-8")

    print(f"{len(rows)} images rewritten to {RAW_BASE}/img/...")
    for name in ("ARTICLE_MEDIUM.md", "medium_paste.html", "IMAGES.md"):
        print(f"  wrote docs/medium/{name}")


if __name__ == "__main__":
    main()
